### ISSUE TITLE
仿真激光雷达时，如果Gazebo使用的是dart引擎，雷达扫描会穿过物体。但是使用ode可以正常使用不会穿过物体 When simulating laser radar, if Gazebo uses a dart engine, the radar scan will pass through the object. But it can be used normally without passing through objects

### ISSUE THREAD

**Issue by huqin-RM** [osrf/gazebo#3304] opened 2023-03-10 16:13 UTC
![16D99B22-6EE4-4E58-A199-0D5C316455D2](https://user-images.githubusercontent.com/72855121/224366585-1d6fcdca-0e8c-4db3-9f64-210fa0bf6034.png)
![EC28B174-1850-4F04-A999-25D02175CF0F](https://user-images.githubusercontent.com/72855121/224366637-59c43e9d-850a-48bd-a205-51e1a32afccf.png)

When simulating laser radar, if Gazebo uses a dart engine, the radar scan will pass through the object. But it can be used normally without passing through objects

**Comment by traversaro** [comment] 2023-03-11 07:15
I am afraid this is a duplicate of https://github.com/gazebosim/gazebo-classic/issues/911 . Did you tried with gpu_ray ?

**Comment by huqin-RM** [comment] 2023-03-15 13:35
> I am afraid this is a duplicate of #911 . Did you tried with gpu_ray ?


My computer doesn't seem to find gpu ray. How it should be used

**Comment by huqin-RM** [comment] 2023-03-15 13:43
using the ode engine can work normally without passing through objects

**Comment by traversaro** [comment] 2023-03-15 13:46
> using the ode engine can work normally without passing through objects

Then I think it is a duplicate of https://github.com/gazebosim/gazebo-classic/issues/911 .

> > I am afraid this is a duplicate of #911 . Did you tried with gpu_ray ?
> 
> My computer doesn't seem to find gpu ray. How it should be used

See https://github.com/gazebosim/gazebo-classic/blob/d3584008b47c745c1732a6cd07af68726cd900fa/test/worlds/gpu_laser2.world#L43 for an example. 


Given that this is a duplicate issue, I think we can close the issue, what do you think?

**Comment by huqin-RM** [comment] 2023-03-15 14:12
> > using the ode engine can work normally without passing through objects
> 
> Then I think it is a duplicate of #911 .
> 
> > > I am afraid this is a duplicate of #911 . Did you tried with gpu_ray ?
> > 
> > 
> > My computer doesn't seem to find gpu ray. How it should be used
> 
> See
> 
> https://github.com/gazebosim/gazebo-classic/blob/d3584008b47c745c1732a6cd07af68726cd900fa/test/worlds/gpu_laser2.world#L43
> 
> for an example.
> Given that this is a duplicate issue, I think we can close the issue, what do you think?

Does Dart engine not support the use of ray related plug-ins at present

**Comment by traversaro** [comment] 2023-03-15 14:28
> Does Dart engine not support the use of ray related plug-ins at present

No, this is exactly the issue tracked at https://github.com/gazebosim/gazebo-classic/issues/911 .

**Comment by huqin-RM** [comment] 2023-03-15 14:36
> 

At present, can anyone successfully use ray under the dart engine?

**Comment by traversaro** [comment] 2023-03-15 14:53
No, because the relevant code is not implemented, see https://github.com/gazebosim/gazebo-classic/issues/911 . I will close this issue, if you have more thing to add feel free to write them in https://github.com/gazebosim/gazebo-classic/issues/911, thanks!

**Closed as completed by traversaro** 2023-03-15 14:53 UTC
Labels: bug

**Comment by huqin-RM** [comment] 2023-03-15 15:08
> No, because the relevant code is not implemented, see #911 . I will close this issue, if you have more thing to add feel free to write them in #911, thanks!

Ok
