### ISSUE TITLE
11.15.0 Update Broke Spawn Model---Cannot run simulation for class

### ISSUE THREAD

**Issue by leegs** [osrf/gazebo#3411] opened 2024-12-02 21:51 UTC
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
This is the binary build of gazebo11_11.15.0-1~focal.  

## Description

Gazebo is being used in a college course at CWRU and students cannot demonstrate code that works with Gazebo 11.14 if they have updated 11.15.  Please rollback functionality to 11.14 as quickly as possible.  

When spawning models after the 11.15 update, models do not spawn.  The spawning of the robot models into Gazebo is hanging and not returning.

## Steps to reproduce

The specific steps to reproduce this requires using a package set of packages prepared for the course.  It is likely that spawning other models has the same effect, but cannot determine right now.  Installing the ros-noetic-ecse-373-ariac package from this repository and running roslaunch ecse-373-ariac ecse-373-ariac.launch should reproduce the error.

Instructions for the course repository are here:
     https://cwru-ecse-373.github.io/

## Output

The spawn_model node hangs and the model does not appear in Gazebo.

**Comment by traversaro** [comment] 2024-12-02 22:30
Probably this is related to https://github.com/gazebosim/gazebo-classic/issues/3409 .

**Comment by traversaro** [comment] 2024-12-02 22:34
Are you able to replicate the problem without using ROS functionality? If not, it probably could make sense to also open an issue in https://github.com/ros-simulation/gazebo_ros_pkgs ?

In the meanwhile, you may want to pin the gazebo version you are using to 11.14.0 if that version is working for you. I am not familiar how to do that with apt, but I guess it should be possible: https://help.ubuntu.com/community/PinningHowto .

**Comment by traversaro** [comment] 2024-12-02 22:37
I wonder if this may be related to https://github.com/gazebosim/gazebo-classic/pull/3374 ? fyi @scpeters

**Comment by traversaro** [comment] 2024-12-02 22:44
> In the meanwhile, you may want to pin the gazebo version you are using to 11.14.0 if that version is working for you. I am not familiar how to do that with apt, but I guess it should be possible: https://help.ubuntu.com/community/PinningHowto .

Probably @j-rivero may know more about this.

**Comment by MilkyWay2001** [comment] 2024-12-02 23:32
Hello, have you solved it? I have the same problem.

**Comment by azeey** [comment] 2024-12-03 05:42
I'm not sure why, but building gazebo_ros_pkgs from source with the new version of Gazebo11 fixes the problem for me.

**Comment by scpeters** [comment] 2024-12-03 05:49
> I'm not sure why, but building gazebo_ros_pkgs from source with the new version of Gazebo11 fixes the problem for me.

maybe an ABI change from https://github.com/gazebosim/gazebo-classic/pull/3283?

**Comment by vigneshmgz** [comment] 2024-12-03 06:08
I'm also facing the same issue, yes it is working when building local, so is there any current development going on in noetic devel of `gazebo-ros-pkgs` but not released yet, that is considered in the relase of `gazebo 11.15.0`?

The last release of `gazebo-ros-pkgs` is on July, but the commits are upto Sep. So this changes are able to fix the issue right? @azeey

**Comment by scpeters** [comment] 2024-12-03 06:34
> > I'm not sure why, but building gazebo_ros_pkgs from source with the new version of Gazebo11 fixes the problem for me.
> 
> maybe an ABI change from #3283?

testing whether #3283 broke ABI in https://github.com/gazebosim/gazebo-classic/pull/3412

**Comment by hitsz-qfy** [comment] 2024-12-03 07:37
same problem, and build `gazebo-ros-pkgs` from source in noetic branch work

**Comment by azeey** [comment] 2024-12-03 09:00
I can confirm that the regression is caused by #3283 and I think it's an "ABI" issue as @scpeters suggested. However, I'm not sure it's a typical ABI issue since it involves templates. This is what I did to test.
1. Remove any existing versions of Gazebo11
1. Checkout and build version 11.11.0 since that's what's currently available in packages.ros.org and what `gazebo_ros_pkgs` is built against. Install to `/usr`
2. Build `gazebo_ros_pkgs` 
3. Verify that spawning works (this should work).
4. Checkout e65ed2e (commit for #3283) in Gazebo11, build, and install it.
5. **Without** rebuilding `gazebo_ros_pkgs` check if spawning works. This did not work for me.
6. Checkout 9b72949 (11.14.0 or e65ed2e~1) in Gazebo11, build, and install it.
7. **Without** rebuilding `gazebo_ros_pkgs` check if spawning works. This works for me.

Note that rebuilding `gazebo_ros_pkgs` with any of the versions fixes the problem, so I'm convinced it's an ABI problem, albeit a weird, template related one.

I used a modified launch file from https://github.com/gazebosim/gazebo-classic/issues/3409

```xml
<?xml version="1.0"?>
<launch>

    <arg name="verbose" default="true"/>
    <arg name="sdf" />

    <!-- Gazebo sim -->
    <include file="$(find gazebo_ros)/launch/empty_world.launch">
        <arg name="gui" value="false"/>
        <arg name="debug" value="false"/>
        <arg name="verbose" value="$(arg verbose)"/>
        <arg name="paused" value="false"/>
        <arg name="respawn_gazebo" value="false"/>
    </include>
    <!-- gazebo model -->
    <node name="$(anon vehicle_spawn)" pkg="gazebo_ros" type="spawn_model" output="screen" args="-sdf -file $(arg sdf) -model test_model"/>
</launch>
```

And ran it with `roslaunch ./test.launch sdf:=$HOME/ws/gazebo-classic/test/models/box.sdf`. 

My suggestion is to revert #3283, make a release, and then in a follow-up PR, look into fixing the armhf issue. Perhaps we can wrap the whole `GZ_SINGLETON_DECLARE` block in an ifdef that detects if the architecture is armhf.

**Comment by hitsz-qfy** [comment] 2024-12-03 09:01
您好，     邮件已收到。

**Comment by j-rivero** [comment] 2024-12-03 11:44
> In the meanwhile, you may want to pin the gazebo version you are using to 11.14.0 if that version is working for you. I am not familiar how to do that with apt, but I guess it should be possible: https://help.ubuntu.com/community/PinningHowto .

The pinning workaround would be the best solution until we resolve the issue, yes.

> My suggestion is to revert #3283, make a release, and then in a follow-up PR, look into fixing the armhf issue. Perhaps we can wrap the whole `GZ_SINGLETON_DECLARE` block in an ifdef that detects if the architecture is armhf.

I agree. I'm going to merge #3412 and release a 11.15.1 version.

**Comment by j-rivero** [comment] 2024-12-03 19:35
11.15.1 Gazebo should be in the repo. Can anyone please confirm if it is working as expected?

**Comment by leegs** [comment] 2024-12-03 20:26
Working!  Thank you for the quick response!!

**Comment by MilkyWay2001** [comment] 2024-12-04 10:15
> 11.15.1 Gazebo should be in the repo. Can anyone please confirm if it is working as expected?

Problem solved. Thank you for your efforts.

**Comment by traversaro** [comment] 2024-12-04 10:39
Thanks a lot @j-rivero and @scpeters ! Closing the issue as we received feedback that the deployed fix is working.

**Closed as completed by traversaro** 2024-12-04 10:39 UTC
Labels: bug
