### ISSUE TITLE
Gazebo crashes every time while adding a window/door in Building Editor

### ISSUE THREAD

**Issue by zeeshannisar** [osrf/gazebo#2749] opened 2020-06-07 10:37 UTC
Following the [Tutorial](http://gazebosim.org/tutorials?tut=building_editor&cat=build_world), I am trying to create an environment with multiple rooms. While using Building Editor, Gazebo crashes each time when I am trying to add windows/doors to 2D view after creating the walls. 
I am using Ubuntu 20.04 LTS operating system and installed the gazebo following the installation tutorial at [Here](http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install).

**Comment by chapulina** [comment] 2020-08-12 17:17
I think this is a duplicate of #2276

**Closed as completed by chapulina** 2020-08-12 17:17 UTC
Labels: bug, gui::BuildingEditor
