### ISSUE TITLE
gazebo installation on Windows 11 (conda-forge) gazebo==11.14.0=*_10 unsuccessful

### ISSUE THREAD

**Issue by aiswaryame94** [osrf/gazebo#3379] opened 2024-04-03 10:14 UTC
Here are the steps I followed to install and run gazebo 11.14 on windows 11.
```
conda create -n gazebo_env
conda activate gazebo_env
conda install conda-forge::gazebo
gazebo --verbose
```
I get the following errors:
![Screenshot 2024-04-02 210936](https://github.com/gazebosim/gazebo-classic/assets/69002589/e5f779a6-4510-4373-a032-1e7b27ebeb0f)
![Screenshot 2024-04-02 211026](https://github.com/gazebosim/gazebo-classic/assets/69002589/81ff208a-068f-42e4-b5a3-85ecb4ef314a)

I also have paused the antivirus protection (Kaspersky), disabled windows firewall, toggled off the real-time protection on windows security. I also set gzserver.exe and gzclient.exe to use hig-processing NVIDIA graphics card,  in the NVIDIA control panel.

I am still facing the same error. Could you kindly help me solve the same?

**Comment by traversaro** [comment] 2024-04-03 21:35
Can you please report the output of:
* conda info 
* conda list
* set 

Thanks!

**EDIT: for anyone looking for a quick solution, a known workaround is to install a version of gazebo compatible with boost 1.82.0, i.e.:**
~~~
conda create -n gazebo gazebo libboost==1.82.0
~~~

**Comment by ShadowDawg** [comment] 2024-04-06 05:08
Hi, I've run into the same issue while installing gazebo 11.14.0. 
conda info: 
```
active environment : gazebo_env
    active env location : C:\Users\shado\miniconda3\envs\gazebo_env
            shell level : 2
       user config file : C:\Users\shado\.condarc
 populated config files : C:\Users\shado\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __cuda=12.3=0
                          __win=0=0
       base environment : C:\Users\shado\miniconda3  (writable)
      conda av data dir : C:\Users\shado\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\shado\miniconda3\pkgs
                          C:\Users\shado\.conda\pkgs
                          C:\Users\shado\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\shado\miniconda3\envs
                          C:\Users\shado\.conda\envs
                          C:\Users\shado\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22000 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
          administrator : False
             netrc file : None
           offline mode : False
```

conda list:
```
# packages in environment at C:\Users\shado\miniconda3\envs\gazebo_env:
#
# Name                    Version                   Build  Channel
aom                       3.8.2                h63175ca_0    conda-forge
assimp                    5.3.1                h0dbab56_3    conda-forge
aws-c-auth                0.7.16               h7613915_8    conda-forge
aws-c-cal                 0.6.10               hf6fcf4e_2    conda-forge
aws-c-common              0.9.14               hcfcfb64_0    conda-forge
aws-c-compression         0.2.18               hf6fcf4e_2    conda-forge
aws-c-event-stream        0.4.2                h3df98b0_6    conda-forge
aws-c-http                0.8.1                h4e3df0f_7    conda-forge
aws-c-io                  0.14.6               hf0b8b6f_2    conda-forge
aws-c-mqtt                0.10.3               h96fac68_2    conda-forge
aws-c-s3                  0.5.4                h08df315_0    conda-forge
aws-c-sdkutils            0.1.15               hf6fcf4e_2    conda-forge
aws-checksums             0.1.18               hf6fcf4e_2    conda-forge
aws-crt-cpp               0.26.4               hbe739fa_2    conda-forge
aws-sdk-cpp               1.11.267             hfaf0dd0_4    conda-forge
azure-core-cpp            1.11.1               h249a519_1    conda-forge
azure-storage-blobs-cpp   12.10.0              h91493d7_1    conda-forge
azure-storage-common-cpp  12.5.0               h91493d7_4    conda-forge
blosc                     1.21.5               hdccc3a2_0    conda-forge
bullet-cpp                3.25                 h2ab9e98_2    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
c-ares                    1.28.1               hcfcfb64_0    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
cfitsio                   4.4.0                h9b0cee5_0    conda-forge
console_bridge            1.0.2                h5362a0b_1    conda-forge
cppzmq                    4.10.0               h42135b4_1    conda-forge
dartsim                   6.13.2               hf6eeb0b_1    conda-forge
dav1d                     1.2.1                hcfcfb64_0    conda-forge
dirent                    1.21                          0    conda-forge
dlfcn-win32               1.4.1                h63175ca_0    conda-forge
eigen                     3.4.0                h91493d7_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
fcl                       0.7.0                he22821c_4    conda-forge
ffmpeg                    6.1.1           gpl_hb766fab_106    conda-forge
flann                     1.9.2                h23e6bae_0    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeglut                  3.2.2                h63175ca_2    conda-forge
freeimage                 3.18.0              h2b56e36_20    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
gazebo                    11.14.0             hb27d4c6_10    conda-forge
geos                      3.12.1               h1537add_0    conda-forge
geotiff                   1.7.1               hed9d743_16    conda-forge
getopt-win32              0.1                  hcfcfb64_1    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.80.0               h39d0aa6_1    conda-forge
glib-tools                2.80.0               h0a98069_1    conda-forge
graphite2                 1.3.13            h63175ca_1003    conda-forge
graphviz                  9.0.0                h51cb2cd_1    conda-forge
gst-plugins-base          1.22.9               h001b923_1    conda-forge
gstreamer                 1.22.9               hb4038d2_1    conda-forge
gts                       0.7.6                h6b5321d_4    conda-forge
harfbuzz                  8.3.0                h7ab893a_0    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_h73e8ff5_100    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
imath                     3.1.11               h12be248_0    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jxrlib                    1.1                  hcfcfb64_3    conda-forge
kealib                    1.5.3                hd248416_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20240116.1      cxx17_h63175ca_2    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarchive                3.7.2                h313118b_1    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libboost                  1.84.0               hcc118f5_2    conda-forge
libboost-devel            1.84.0               h91493d7_2    conda-forge
libboost-headers          1.84.0               h57928b3_2    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libccd-double             2.1                  h63175ca_3    conda-forge
libclang13                18.1.2          default_hf64faad_1    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.7.1                hd5e4a3a_0    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgd                     2.3.3                h312136b_9    conda-forge
libgdal                   3.8.4                hbda495f_6    conda-forge
libglib                   2.80.0               h39d0aa6_1    conda-forge
libgoogle-cloud           2.22.0               h9cad5c0_1    conda-forge
libgoogle-cloud-storage   2.22.0               hb581fae_1    conda-forge
libgrpc                   1.62.1               h5273850_0    conda-forge
libhwloc                  2.9.3           default_haede6df_1009    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libignition-cmake2        2.16.0               h63175ca_1    conda-forge
libignition-common3       3.15.1               hef572a9_3    conda-forge
libignition-fuel-tools4   4.6.0                h7d73f36_9    conda-forge
libignition-math6         6.15.1          py312haf63811_1    conda-forge
libignition-msgs5         5.11.0               h76d1f87_9    conda-forge
libignition-tools1        1.5.0                hf5993cb_3    conda-forge
libignition-transport8    8.4.0               h401e20c_11    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             haf3e7a6_1018    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
libnetcdf                 4.9.2           nompi_h07c049d_113    conda-forge
libode                    0.16.2              h53d5487_14    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopenblas               0.3.26          pthreads_hc140b1d_0    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpq                     16.2                 hdb24f17_1    conda-forge
libprotobuf               4.25.3               h503648d_0    conda-forge
libraw                    0.21.1               h5557f11_2    conda-forge
libre2-11                 2023.09.01           hf8d8778_2    conda-forge
librttopo                 1.1.0               h94c4f80_15    conda-forge
libsdformat               9.8.0                hbbad600_6    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialite             5.1.0                hf13de1f_5    conda-forge
libsqlite                 3.45.2               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libusb                    1.0.27             hcfcfb64_100    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.12.6               hc3477c8_1    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
minizip                   4.0.5                h5bed578_0    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.26.4          py312h8753938_0    conda-forge
octomap                   1.9.8                h91493d7_0    conda-forge
ogre                      1.10.12.1            hc646683_0    conda-forge
openal-soft               1.23.1               h91493d7_0    conda-forge
openblas                  0.3.26          pthreads_h3721920_0    conda-forge
openexr                   3.2.2                h72640d8_1    conda-forge
openh264                  2.4.1                h63175ca_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
pango                     1.52.2               h07c897b_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
poppler                   24.03.0              hc2f3c52_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.2                 h94c9ec1_1    conda-forge
proj                      9.4.0                he13c7e8_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pugixml                   1.14                 h63175ca_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
python                    3.12.2          h2628c8c_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
qt-main                   5.15.8              h9e85ed6_20    conda-forge
qwt                       6.2.0                h07be427_6    conda-forge
re2                       2023.09.01           hd3b24a8_2    conda-forge
ruby                      3.2.2                h20ad4f3_1    conda-forge
sdl2                      2.30.2               h63175ca_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
simbody                   3.7                  hade3207_3    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
spdlog                    1.12.0               h64d2f7d_2    conda-forge
sqlite                    3.45.2               hcfcfb64_0    conda-forge
svt-av1                   1.8.0                h63175ca_0    conda-forge
tbb                       2021.11.0            h91493d7_1    conda-forge
tbb-devel                 2021.11.0            h3ec46f0_1    conda-forge
tiledb                    2.21.1               h25b666a_1    conda-forge
tiny-process-library      2.0.4                h63175ca_1    conda-forge
tinyxml                   2.6.2                h2d74725_2    conda-forge
tinyxml2                  10.0.0               h63175ca_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urdfdom                   4.0.0                h0b06ded_1    conda-forge
urdfdom_headers           1.1.1                h91493d7_0    conda-forge
uriparser                 0.9.7                h1537add_1    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xerces-c                  3.2.5                h63175ca_0    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.1.1                hcd874cb_0    conda-forge
xorg-libsm                1.2.4                hcd874cb_0    conda-forge
xorg-libx11               1.8.7                hefa74cf_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_2    conda-forge
xorg-libxpm               3.5.17               hcd874cb_0    conda-forge
xorg-libxt                1.3.0                hcd874cb_1    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.5                h63175ca_1    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
zziplib                   0.13.69              h1d00b33_1    conda-forge
```

set:
```
ACSvcPort=17532
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\shado\AppData\Roaming
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=133471907338717603
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SHADOW
ComSpec=C:\Windows\system32\cmd.exe
CONDA_DEFAULT_ENV=gazebo_env
CONDA_EXE=C:\Users\shado\miniconda3\condabin\..\Scripts\conda.exe
CONDA_EXES="C:\Users\shado\miniconda3\condabin\..\Scripts\conda.exe"
CONDA_PREFIX=C:\Users\shado\miniconda3\envs\gazebo_env
CONDA_PREFIX_1=C:\Users\shado\miniconda3
CONDA_PROMPT_MODIFIER=(gazebo_env)
CONDA_PYTHON_EXE=C:\Users\shado\miniconda3\python.exe
CONDA_SHLVL=2
DriverData=C:\Windows\System32\Drivers\DriverData
EnableLog=INFO
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
GAZEBO_MASTER_URI=http://localhost:11345
GAZEBO_MODEL_DATABASE_URI=http://models.gazebosim.org
GAZEBO_MODEL_PATH=C:/Users/shado/miniconda3/envs/gazebo_env/Library/share/gazebo-11/models;C:\Users\shado\OneDrive\Desktop\work\synapse-gazebo\src\robot\universal_robotics\ur5_gazebo\gazebo_model
GAZEBO_PLUGIN_PATH=C:/Users/shado/miniconda3/envs/gazebo_env/Library/bin/gazebo-11/plugins;C:\Users\shado\OneDrive\Desktop\work\synapse-gazebo\build\src\robot\universal_robotics\ur5_gazebo\gazebo_plugin\Release
GAZEBO_RESOURCE_PATH=C:/Users/shado/miniconda3/envs/gazebo_env/Library/share/gazebo-11;
GDAL_DATA=C:\Users\shado\miniconda3\envs\gazebo_env\Library\share\gdal
GDAL_DRIVER_PATH=C:\Users\shado\miniconda3\envs\gazebo_env\Library\lib\gdalplugins
GEM_HOME=C:\Users\shado\miniconda3\envs\gazebo_env\share\rubygems
GEOTIFF_CSV=C:\Users\shado\miniconda3\envs\gazebo_env\Library\share\epsg_csv
HOME=C:\Users\shado
HOMEDRIVE=C:
HOMEPATH=\Users\shado
JD2_HOME=C:\Users\shado\AppData\Local\JDownloader 2.0
LD_LIBRARY_PATH=;C:/Users/shado/miniconda3/envs/gazebo_env/Library/bin/gazebo-11/plugins
LOCALAPPDATA=C:\Users\shado\AppData\Local
LOGONSERVER=\\SHADOW
NUMBER_OF_PROCESSORS=16
OGRE_RESOURCE_PATH=C:/Users/shado/miniconda3/envs/gazebo_env/Library/bin
OneDrive=C:\Users\shado\OneDrive
OS=Windows_NT
Path=C:\Users\shado\miniconda3\envs\gazebo_env\share\rubygems\bin;;C:/Users/shado/miniconda3/envs/gazebo_env/Library/bin/gazebo-11/plugins;C:\Users\shado\miniconda3\envs\gazebo_env;C:\Users\shado\miniconda3\envs\gazebo_env\Library\mingw-w64\bin;C:\Users\shado\miniconda3\envs\gazebo_env\Library\usr\bin;C:\Users\shado\miniconda3\envs\gazebo_env\Library\bin;C:\Users\shado\miniconda3\envs\gazebo_env\Scripts;C:\Users\shado\miniconda3\envs\gazebo_env\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet;C:\Program Files\PuTTY;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\Calibre2;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\Users\shado\AppData\Local\Pub\Cache\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Users\shado\miniconda3\condabin;C:\Users\shado\Downloads\oneapi-tbb-2021.11.0-win\oneapi-tbb-2021.11.0\lib\intel64\vc14;C:\MinGW\bin;C:\swigwin-3.0.12;C:\Python\Scripts;C:\Python;C:\Users\shado\AppData\Local\Programs\Python\Launcher;C:\Users\shado\AppData\Local\Microsoft\WindowsApps;C:\Users\shado\AppData\Local\Programs\Microsoft VS Code\bin;C:\src\flutter\flutter\bin;C:\Users\shado\AppData\Roaming\npm;C:\MinGW\bin;C:\Users\shado\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\shado\AppData\Local\GitHubDesktop\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9a03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROJ_DATA=C:\Users\shado\miniconda3\envs\gazebo_env\Library\share\proj
PROJ_NETWORK=ON
PROMPT=(gazebo_env) $P$G
PSModulePath=C:\Users\shado\Documents\WindowsPowerShell\Modules;C:\Users\shado\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell
PUBLIC=C:\Users\Public
RlsSvcPort=22112
SDF_PATH=C:\Users\shado\miniconda3\envs\gazebo_env\Library\share\sdformat9\1.7
SESSIONNAME=Console
SSL_CERT_FILE=C:\Users\shado\miniconda3\Library\ssl\cacert.pem
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\shado\AppData\Local\Temp
TMP=C:\Users\shado\AppData\Local\Temp
USERDOMAIN=SHADOW
USERDOMAIN_ROAMINGPROFILE=SHADOW
USERNAME=shado
USERPROFILE=C:\Users\shado
windir=C:\Windows
XML_CATALOG_FILES=file:///C:/Users/shado/miniconda3/envs/gazebo_env/etc/xml/catalog
ZES_ENABLE_SYSMAN=1
__CONDA_OPENSLL_CERT_FILE_SET="1"
```

But I've only faced this error intalling the latest version (11.14.0) and 11.13.0 runs fine!

**Comment by traversaro** [comment] 2024-04-06 14:06
Thanks, I was able to reproduce the problem.

**Comment by traversaro** [comment] 2024-04-06 14:18
The 0xc0000142 error means that some dll is not loaded, let's debug with https://github.com/lucasg/Dependencies .

**Comment by traversaro** [comment] 2024-04-06 14:18
Not even `gz` works.

**Comment by traversaro** [comment] 2024-04-06 14:27
Installing `gazebo==11.14.0=*_9` works fine, so it could be something related to boost or similar:

~~~
(gazebo) C:\Users\straversaro>mamba install gazebo==11.14.0=*_9

Looking for: ['gazebo==11.14.0[build=*_9]']

conda-forge/noarch                                  14.2MB @   7.2MB/s  2.0s
conda-forge/win-64                                  21.5MB @   7.3MB/s  3.0s

Pinned packages:
  - python 3.12.*
Transaction

  Prefix: C:\Users\straversaro\AppData\Local\miniforge3\envs\gazebo

  Updating specs:

   - gazebo==11.14.0[build=*_9]
   - ca-certificates
   - openssl


  Package             Version  Build        Channel           Size
--------------------------------------------------------------------
  Change:
--------------------------------------------------------------------

  - assimp              5.3.1  h0dbab56_3   conda-forge     Cached
  + assimp              5.3.1  h81f0834_2   conda-forge     Cached
  - gazebo            11.14.0  hb27d4c6_10  conda-forge     Cached
  + gazebo            11.14.0  h3902e0a_9   conda-forge       60MB

  Downgrade:
--------------------------------------------------------------------

  - libboost           1.84.0  hcc118f5_2   conda-forge     Cached
  + libboost           1.82.0  h65993cd_6   conda-forge     Cached
  - libboost-headers   1.84.0  h57928b3_2   conda-forge     Cached
  + libboost-headers   1.82.0  h57928b3_6   conda-forge     Cached
  - libboost-devel     1.84.0  h91493d7_2   conda-forge     Cached
  + libboost-devel     1.82.0  h91493d7_6   conda-forge     Cached

  Summary:

  Change: 2 packages
  Downgrade: 3 packages

  Total download: 60MB

--------------------------------------------------------------------


Confirm changes: [Y/n] y
gazebo                                              60.3MB @  12.3MB/s  4.9s

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: -
Executing transaction: done

**Comment by traversaro** [comment] 2024-04-06 15:16
> The 0xc0000142 error means that some dll is not loaded, let's debug with https://github.com/lucasg/Dependencies .

I do not see anything clearly wrong with that. I wonder if this problem is somehow related to https://github.com/robotology/gazebo-yarp-plugins/issues/678 .

**Comment by traversaro** [comment] 2024-04-07 07:34
The problem is present with all builds of libboost 1.84.0, so probably the problem is not related to some ABI break between different builds of libboost 1.84.0 . The problem is not present in Linux/macOS.

**Comment by traversaro** [comment] 2024-04-08 21:32
Some updates: https://github.com/conda-forge/gazebo-feedstock/pull/210#issuecomment-2043671771 : 

> I tested this locally, and it has the exact same problem of boost 1.84 builds, even if we are using boost 1.82 . On the other hand, I built locally gazebo-classic against 1.84, and it is working fine. At this point, I suspect that the difference between working and not working builds is the visual studio version, that got updated at some point between 1.82 and 1.84 builds.

First problematic build: https://github.com/conda-forge/gazebo-feedstock/runs/23137603666, compiled with MSVC 19.38.33135.0
Last successful build: https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/896987/logs/55 MSVC 19.29.30154.0

Ok, ~the MSVC is exactly the same~ Edit, I was looking at the wrong job. Indeed the MSVC version is different, I wonder if it is something related to this comment https://github.com/conda-forge/conda-forge.github.io/issues/2102#issuecomment-2043560833 .

**Comment by traversaro** [comment] 2024-04-08 21:40
> Ok, ~the MSVC is exactly the same~ Edit, I was looking at the wrong job. Indeed the MSVC version is different, I wonder if it is something related to this comment [conda-forge/conda-forge.github.io#2102 (comment)](https://github.com/conda-forge/conda-forge.github.io/issues/2102#issuecomment-2043560833) .

Note that this (i.e. the use of vs2022) does not explain by itself the problem, it is probably some sort of regression in the vs2022 version used in the CI. However, for sure this explains why a downstream vs2019 build failed, see https://github.com/robotology/gazebo-yarp-plugins/pull/679 .

**Comment by traversaro** [comment] 2024-04-08 21:47
> The 0xc0000142 error means that some dll is not loaded, let's debug with https://github.com/lucasg/Dependencies .

For future reference: this was wrong. The dll not loaded/missing symbols error is 0xc0000135, 0xc0000142 is something like "application not starting correctly" or something similar.

**Comment by h-vetinari** [comment] 2024-04-09 06:03
If indeed this has something to do with vs2022, you should now be able to rerender & rebuild the respective feedstocks, and hopefully the problem will then disappear. Sorry for the trouble!

**Comment by traversaro** [comment] 2024-04-09 06:55
> If indeed this has something to do with vs2022, you should now be able to rerender & rebuild the respective feedstocks, and hopefully the problem will then disappear. Sorry for the trouble!

No problem! Indeed, I will open an issue to track the problem with vs2022, it is possible that just updating to a more recent version of vs2022 the problem disappears. Or let's hope that everyone stopped using gazebo classic and moved to gz-sim by the time that conda-forge migrates to vs2022.

**Comment by traversaro** [comment] 2024-04-10 10:00
The problem should be fixed with the `gazebo==11.14.0=orignameh160ba46_212` and `gazebo==11.14.0=gzcompatnameh1a9e25f_12` builds, i.e. now:

~~~
conda create -n gazebo gazebo
~~~

should work out of the box. Thanks a lot @aiswaryame94 and @ShadowDawg for reporting the problem, it was a tricky one. We also added tests in https://github.com/conda-forge/gazebo-feedstock/pull/211 to avoid these kind of regressions.

**Closed as completed by traversaro** 2024-04-10 10:00 UTC

**Comment by USeebi** [comment] 2024-08-13 13:01
I  got the same errors on all solutions stipulated including, 

conda create -n gazebo gazebo==11.14.0=*_9

conda create -n gazebo gazebo==11.14.0=orignameh160ba46_212

conda create -n gazebo gazebo==11.14.0=gzcompatnameh1a9e25f_12
Is _12 a typo?

Any update on a working gazebo classic distribution from conda-forge for Windows 11?  I don't have problem with that in Windows 10, why Win 11 only?
Any hints?

Many thanks!

**Comment by traversaro** [comment] 2024-08-13 13:16
@USeebi can you open a new issue following the template? It is easier to track problems as new issue, as opposed to closed issues, thanks!
